platform: ${platform}

clone:
  git:
    image: ${git}
    depth: 50

pipeline:
  rootfs:
    image: ${container}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./bootstrap/bootstrap.sh ${arch}
      - ./upload-artifact.sh rootfs-${arch}.tar.gz
    privileged: true
  
  syncloud-rootfs:
    image: ${container}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./rootfs.sh ${arch} rc stable
      - ./upload-artifact.sh syncloud-rootfs-${arch}.tar.gz
    privileged: true
    
  image:
    image: ${container}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./extract/extract.sh cubietruck
      - ./merge.sh cubietruck ${arch}
    privileged: true
     
matrix:
  include:
    - platform: linux/arm
      container: armv7/armhf-debian:8
      git: syncloud/armhf-drone-git
      arch: armhf
    - platform: linux/amd64
      container: debian:8
      git: plugins/git
      arch: amd64
