---
kind: pipeline
name: beagleboneblack

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge.sh beagleboneblack arm beagleboneblack-base.img syncloud-beagleboneblack-19.10.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-beagleboneblack-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh beagleboneblack-base.img
  - ./cleanup.sh syncloud-beagleboneblack-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

...
