platform: linux/amd64

clone:
  git:
    image: syncloud/drone-git-amd64
    depth: 50

pipeline:
  image:
    secrets: [ARTIFACT_SSH_KEY, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    image: syncloud/build-deps-amd64
    commands:
      - RELEASE="18.12"
      - echo "${board}-base.img" > BASE_IMAGE
      - echo "syncloud-${board}-$RELEASE.img" > IMAGE
      - ./extract-merge-upload.sh ${board} ${arch} `cat BASE_IMAGE` `cat IMAGE`
    privileged: true

  cleanup:
    image: syncloud/build-deps-amd64
    commands:
      - ./cleanup.sh `cat BASE_IMAGE`
      - ./cleanup.sh `cat IMAGE`
    privileged: true
    when:
      status: [ failure, success ] 

     
matrix:
  include:
    - board: rock64
      arch: arm
    - board: helios4
      arch: arm
    - board: raspberrypi3
      arch: arm
    - board: raspberrypi2
      arch: arm
    - board: odroid-xu3and4
      arch: arm
    - board: odroid-c2
      arch: arm
    - board: cubieboard2
      arch: arm
    - board: cubieboard
      arch: arm
    - board: bananapim3
      arch: arm
    - board: bananapim2
      arch: arm
    - board: beagleboneblack
      arch: arm
    - board: bananapim1
      arch: arm
    - board: cubietruck
      arch: arm
    - board: tinker
      arch: arm
    - board: vbox
      arch: amd64
