---
kind: pipeline
name: odroid-c2-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh odroid-c2 odroid-c2-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh odroid-c2 syncloud-odroid-c2-21.01.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/rootfs.sh odroid-c2 arm syncloud-odroid-c2-21.01.img 21.01 buster
  privileged: true


- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-odroid-c2-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-odroid-c2-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: odroid-u3-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh odroid-u3 odroid-u3-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh odroid-u3 syncloud-odroid-u3-21.01.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/rootfs.sh odroid-u3 arm syncloud-odroid-u3-21.01.img 21.01 buster
  privileged: true


- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-odroid-u3-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-odroid-u3-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: bananapim2-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh bananapim2 bananapim2-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh bananapim2 syncloud-bananapim2-21.01.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/rootfs.sh bananapim2 arm syncloud-bananapim2-21.01.img 21.01 buster
  privileged: true


- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-bananapim2-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-bananapim2-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: bananapim1-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh bananapim1 bananapim1-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh bananapim1 syncloud-bananapim1-21.01.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/rootfs.sh bananapim1 arm syncloud-bananapim1-21.01.img 21.01 buster
  privileged: true


- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-bananapim1-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-bananapim1-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: cubietruck-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh cubietruck cubietruck-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh cubietruck syncloud-cubietruck-21.01.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/rootfs.sh cubietruck arm syncloud-cubietruck-21.01.img 21.01 buster
  privileged: true


- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-cubietruck-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-cubietruck-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: tinker-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh tinker tinker-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh tinker syncloud-tinker-21.01.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/rootfs.sh tinker arm syncloud-tinker-21.01.img 21.01 buster
  privileged: true


- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-tinker-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-tinker-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: odroid-n2-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh odroid-n2 odroid-n2-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh odroid-n2 syncloud-odroid-n2-21.01.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/rootfs.sh odroid-n2 arm syncloud-odroid-n2-21.01.img 21.01 buster
  privileged: true


- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-odroid-n2-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-odroid-n2-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: lime2-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh lime2 lime2-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh lime2 syncloud-lime2-21.01.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/rootfs.sh lime2 arm syncloud-lime2-21.01.img 21.01 buster
  privileged: true


- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-lime2-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-lime2-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: amd64-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh amd64 amd64-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh amd64 syncloud-amd64-21.01.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/rootfs.sh amd64 amd64 syncloud-amd64-21.01.img 21.01 buster
  privileged: true

- name: virtualbox prepare
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: virtualbox_host
    key:
      from_secret: virtualbox_key
    source:
    - syncloud-amd64-21.01.img
    - create_vbox_image.sh
    target: /data/drone-buster
    username: root

- name: virtualbox
  image: appleboy/drone-ssh
  settings:
    command_timeout: 20m
    host:
      from_secret: virtualbox_host
    key:
      from_secret: virtualbox_key
    port: 22
    script:
    - cd /data/drone-buster
    - ./create_vbox_image.sh syncloud-amd64-21.01.img
    script_stop: true
    username: root
  privileged: true

- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-amd64-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-amd64-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

...
