platform: linux/amd64

clone:
  git:
    image: syncloud/drone-git-amd64
    depth: 50

pipeline:
  image:
    secrets: [ARTIFACT_SSH_KEY, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    image: syncloud/image-deps-amd64
    commands:
      - RELEASE="17.09"
      - ./extract-merge-upload.sh ${board} $RELEASE ${installer} armhf
    privileged: true


#  image_vbox:
#    image: syncloud/image-deps-${arch}
#    secrets: [ARTIFACT_SSH_KEY, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
#    commands:
#      - RELEASE=$(cat release)
#      - ./extract-merge-upload.sh vbox $RELEASE ${installer} amd64
#    privileged: true

     
matrix:
  board:
#    - raspberrypi3
    - raspberrypi2
#    - odroid-xu3and4
#    - odroid-c2
#    - cubieboard2
#    - cubieboard
#    - bananapim3
#    - bananapim2
#    - beagleboneblack
#    - bananapim1
    - cubietruck
  installer:
    - sam
#    - snapd
