---
kind: pipeline
name: rock64

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge.sh rock64 arm rock64-base.img syncloud-rock64-19.11.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-rock64-19.11.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh rock64-base.img
  - ./cleanup.sh syncloud-rock64-19.11.img
  privileged: true
  when:
    status:
    - failure
    - success

...
