platform: linux/${arch}

clone:
  git:
    image: syncloud/drone-git-${arch}
    depth: 50

pipeline:

  version:
    image: syncloud/image-deps-${arch}
    commands:
      - echo "17.09-single" > release
  
  image_cubietruck:
    image: syncloud/image-deps-${arch}
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    commands:
      - RELEASE=$(cat release)
      - ./extract-merge-upload.sh cubietruck $RELEASE ${installer}
    privileged: true


matrix:
  arch:
#    - arm
    - amd64
  installer:
    - sam
#    - snapd
