platform: linux/amd64

clone:
  git:
    image: syncloud/drone-git-amd64
    depth: 50

pipeline:
  image:
    secrets: [ARTIFACT_SSH_KEY, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    image: syncloud/build-deps-amd64
    commands:
      - RELEASE="18.05"
      - echo "${board}-${installer}-base.img" > BASE_IMAGE
      - echo "syncloud-${board}-$RELEASE-${installer}.img" > IMAGE
      - ./extract-merge-upload.sh ${board} ${installer} ${arch} `cat BASE_IMAGE` `cat IMAGE`
    privileged: true

  cleanup:
    image: syncloud/build-deps-amd64
    commands:
      - ./cleanup.sh `cat BASE_IMAGE`
      - ./cleanup.sh `cat IMAGE`
    privileged: true
    when:
      status: [ failure, success ] 
      
      
#  image_vbox:
#    image: syncloud/build-deps-${arch}
#    secrets: [ARTIFACT_SSH_KEY, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
#    commands:
#      - RELEASE=$(cat release)
#      - ./extract-merge-upload.sh vbox $RELEASE ${installer} amd64
#    privileged: true

     
matrix:
  board:
#    - raspberrypi3
    - raspberrypi2
#    - odroid-xu3and4
#    - odroid-c2
#    - cubieboard2
#    - cubieboard
#    - bananapim3
#    - bananapim2
#    - beagleboneblack
#    - bananapim1
#    - cubietruck
#    - tinker
#    - helios4

# not able to run VirtualBox on ScaleWay device hosting 
#   - vbox
  installer:
    - sam
    - snapd
  arch:
    - armhf
#   - amd64
