---
kind: pipeline
name: tinker-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-amd64
  commands:
  - ./tools/extract.sh tinker tinker-base.img buster
  privileged: true

- name: boot
  image: syncloud/build-deps-amd64
  commands:
  - ./tools/boot.sh tinker syncloud-tinker-buster-20.04.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-amd64
  commands:
  - ./tools/rootfs.sh tinker arm syncloud-tinker-buster-20.04.img 20.04 buster
  privileged: true


- name: zip
  image: syncloud/build-deps-amd64
  commands:
  - ./tools/zip.sh syncloud-tinker-buster-20.04.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-tinker-buster-20.04.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: tinker-all-jessie

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-amd64
  commands:
  - ./tools/extract.sh tinker tinker-base.img jessie
  privileged: true

- name: boot
  image: syncloud/build-deps-amd64
  commands:
  - ./tools/boot.sh tinker syncloud-tinker-jessie-20.04.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-amd64
  commands:
  - ./tools/rootfs.sh tinker arm syncloud-tinker-jessie-20.04.img 20.04 jessie
  privileged: true


- name: zip
  image: syncloud/build-deps-amd64
  commands:
  - ./tools/zip.sh syncloud-tinker-jessie-20.04.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-tinker-jessie-20.04.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

...
