---
kind: pipeline
name: odroid-hc4-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh odroid-hc4 odroid-hc4-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh odroid-hc4 syncloud-odroid-hc4-21.01.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/rootfs.sh odroid-hc4 arm syncloud-odroid-hc4-21.01.img 21.01 buster
  privileged: true


- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-odroid-hc4-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-odroid-hc4-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

...
