---
kind: pipeline
name: beagleboneblack

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh beagleboneblack arm beagleboneblack-base.img syncloud-beagleboneblack-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-beagleboneblack-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh beagleboneblack-base.img
  - ./cleanup.sh syncloud-beagleboneblack-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: bananapim3

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh bananapim3 arm bananapim3-base.img syncloud-bananapim3-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-bananapim3-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh bananapim3-base.img
  - ./cleanup.sh syncloud-bananapim3-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: rock64

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh rock64 arm rock64-base.img syncloud-rock64-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-rock64-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh rock64-base.img
  - ./cleanup.sh syncloud-rock64-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: helios4

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh helios4 arm helios4-base.img syncloud-helios4-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-helios4-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh helios4-base.img
  - ./cleanup.sh syncloud-helios4-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: raspberrypi3

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh raspberrypi3 arm raspberrypi3-base.img syncloud-raspberrypi3-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-raspberrypi3-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh raspberrypi3-base.img
  - ./cleanup.sh syncloud-raspberrypi3-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: raspberrypi4

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh raspberrypi4 arm raspberrypi4-base.img syncloud-raspberrypi4-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-raspberrypi4-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh raspberrypi4-base.img
  - ./cleanup.sh syncloud-raspberrypi4-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: raspberrypi2

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh raspberrypi2 arm raspberrypi2-base.img syncloud-raspberrypi2-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-raspberrypi2-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh raspberrypi2-base.img
  - ./cleanup.sh syncloud-raspberrypi2-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: odroid-xu3and4

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh odroid-xu3and4 arm odroid-xu3and4-base.img syncloud-odroid-xu3and4-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-odroid-xu3and4-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh odroid-xu3and4-base.img
  - ./cleanup.sh syncloud-odroid-xu3and4-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: odroid-c2

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh odroid-c2 arm odroid-c2-base.img syncloud-odroid-c2-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-odroid-c2-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh odroid-c2-base.img
  - ./cleanup.sh syncloud-odroid-c2-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: odroid-u3

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh odroid-u3 arm odroid-u3-base.img syncloud-odroid-u3-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-odroid-u3-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh odroid-u3-base.img
  - ./cleanup.sh syncloud-odroid-u3-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: cubieboard2

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh cubieboard2 arm cubieboard2-base.img syncloud-cubieboard2-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-cubieboard2-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh cubieboard2-base.img
  - ./cleanup.sh syncloud-cubieboard2-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: cubieboard

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh cubieboard arm cubieboard-base.img syncloud-cubieboard-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-cubieboard-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh cubieboard-base.img
  - ./cleanup.sh syncloud-cubieboard-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: bananapim2

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh bananapim2 arm bananapim2-base.img syncloud-bananapim2-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-bananapim2-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh bananapim2-base.img
  - ./cleanup.sh syncloud-bananapim2-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: bananapim1

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh bananapim1 arm bananapim1-base.img syncloud-bananapim1-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-bananapim1-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh bananapim1-base.img
  - ./cleanup.sh syncloud-bananapim1-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: cubietruck

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh cubietruck arm cubietruck-base.img syncloud-cubietruck-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-cubietruck-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh cubietruck-base.img
  - ./cleanup.sh syncloud-cubietruck-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: tinker

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh tinker arm tinker-base.img syncloud-tinker-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-tinker-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh tinker-base.img
  - ./cleanup.sh syncloud-tinker-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: odroid-n2

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh odroid-n2 arm odroid-n2-base.img syncloud-odroid-n2-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-odroid-n2-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh odroid-n2-base.img
  - ./cleanup.sh syncloud-odroid-n2-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh amd64 amd64 amd64-base.img syncloud-amd64-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-amd64-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh amd64-base.img
  - ./cleanup.sh syncloud-amd64-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: lime2

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - ./extract-merge-upload.sh lime2 arm lime2-base.img syncloud-lime2-19.10.img
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    password:
      from_secret: artifact_password
    source: syncloud-lime2-19.10.img.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh lime2-base.img
  - ./cleanup.sh syncloud-lime2-19.10.img
  privileged: true
  when:
    status:
    - failure
    - success

...
