platform: ${platform}

clone:
  git:
    image: ${git}
    depth: 50

pipeline:
  rootfs:
    image: syncloud/image-deps-${arch}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./bootstrap/bootstrap.sh ${arch}
      - ./upload-artifact.sh rootfs-${arch}.tar.gz
    privileged: true
 
  syncloud-rootfs:
    image: syncloud/image-deps-${arch}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./rootfs.sh ${arch} rc stable
      - ./upload-artifact.sh syncloud-rootfs-${arch}.tar.gz
    privileged: true
 
  test:
    image: syncloud/image-deps-${arch}
    commands:
      - ./integration/test-docker.sh teamcity@syncloud.it password teamcity master device
    privileged: true
     
  version:
    image: syncloud/image-deps-${arch}
    commands:
      - echo "17.05" > release
  
  image_cubietruck:
    group: image
    image: syncloud/image-deps-${arch}
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    commands:
      - RELEASE=$(cat release)
      - ./extract-merge-upload.sh bananapim1 $RELEASE ${arch} $DRONE_BRANCH
    privileged: true
    when:
      platform: linux/arm
      
  image_bananapim1:
    group: image
    image: syncloud/image-deps-${arch}
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    commands:
      - RELEASE=$(cat release)
      - ./extract-merge-upload.sh bananapim1 $RELEASE ${arch} $DRONE_BRANCH
    privileged: true
    when:
      platform: linux/arm

  image_beagleboneblack:
    group: image
    image: syncloud/image-deps-${arch}
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    commands:
      - RELEASE=$(cat release)
      - ./extract-merge-upload.sh beagleboneblack $RELEASE ${arch} $DRONE_BRANCH
    privileged: true
    when:
      platform: linux/arm

  image_bananapim2:
    group: image
    image: syncloud/image-deps-${arch}
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    commands:
      - RELEASE=$(cat release)
      - ./extract-merge-upload.sh bananapim2 $RELEASE ${arch} $DRONE_BRANCH
    privileged: true
    when:
      platform: linux/arm

  image_bananapim3:
    group: image
    image: syncloud/image-deps-${arch}
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    commands:
      - RELEASE=$(cat release)
      - ./extract-merge-upload.sh bananapim3 $RELEASE ${arch} $DRONE_BRANCH
    privileged: true
    when:
      platform: linux/arm

  image_cubieboard:
    group: image
    image: syncloud/image-deps-${arch}
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    commands:
      - RELEASE=$(cat release)
      - ./extract-merge-upload.sh cubieboard $RELEASE ${arch} $DRONE_BRANCH
    privileged: true
    when:
      platform: linux/arm

  image_cubieboard2:
    group: image
    image: syncloud/image-deps-${arch}
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    commands:
      - RELEASE=$(cat release)
      - ./extract-merge-upload.sh cubieboard2 $RELEASE ${arch} $DRONE_BRANCH
    privileged: true
    when:
      platform: linux/arm

  image_odroid-c2:
    group: image
    image: syncloud/image-deps-${arch}
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    commands:
      - RELEASE=$(cat release)
      - ./extract-merge-upload.sh odroid-c2 $RELEASE ${arch} $DRONE_BRANCH
    privileged: true
    when:
      platform: linux/arm

  image_odroid-xu3and4:
    group: image
    image: syncloud/image-deps-${arch}
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    commands:
      - RELEASE=$(cat release)
      - ./extract-merge-upload.sh odroid-xu3and4 $RELEASE ${arch} $DRONE_BRANCH
    privileged: true
    when:
      platform: linux/arm

  image_raspberrypi2:
    group: image
    image: syncloud/image-deps-${arch}
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    commands:
      - RELEASE=$(cat release)
      - ./extract-merge-upload.sh raspberrypi2 $RELEASE ${arch} $DRONE_BRANCH
    privileged: true
    when:
      platform: linux/arm

  image_raspberrypi3:
    group: image
    image: syncloud/image-deps-${arch}
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    commands:
      - RELEASE=$(cat release)
      - ./extract-merge-upload.sh raspberrypi3 $RELEASE ${arch} $DRONE_BRANCH
    privileged: true
    when:
      platform: linux/arm

  ci-artifact:
    image: syncloud/platform-build-deps-${arch}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./upload-artifact.sh integration/log ci/$DRONE_BUILD_NUMBER-${arch}
    when:
      status: [ failure, success ] 
      
services:
  device:
    image: syncloud/systemd-${arch}
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
     
matrix:
  include:
    - platform: linux/arm
      git: syncloud/armhf-drone-git
      arch: armhf
    - platform: linux/amd64
      git: plugins/git
      arch: amd64
