---
kind: pipeline
name: odroid-u3

platform:
  os: linux
  arch: amd64

steps:
- name: image
  image: syncloud/build-deps-amd64
  commands:
  - RELEASE=19.10
  - "echo odroid-u3-base.img > BASE_IMAGE"
  - "echo syncloud-odroid-u3-$RELEASE.img > IMAGE"
  - ./extract-merge-upload.sh odroid-u3 arm $(cat BASE_IMAGE) $(cat IMAGE)
  environment:
    ARTIFACT_SSH_KEY:
      from_secret: ARTIFACT_SSH_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  privileged: true

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh $(cat BASE_IMAGE)
  - ./cleanup.sh $(cat IMAGE)
  privileged: true
  when:
    status:
    - failure
    - success

...
