platform: ${platform}

clone:
  git:
    image: ${git}
    depth: 50

pipeline:
  rootfs:
    image: ${container}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./bootstrap/bootstrap.sh ${arch}
      - ./upload-artifact.sh rootfs-${arch}.tar.gz
    privileged: true
  
  syncloud-rootfs:
    image: ${container}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./rootfs.sh ${arch} rc stable
      - ./upload-artifact.sh syncloud-rootfs-${arch}.tar.gz
    privileged: true
    
  image-arm:
    image: ${container}
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    commands:
      - RELEASE=17.05
      - ./extract-merge-upload.sh cubietruck $RELEASE ${arch}
      - ./extract-merge-upload.sh bananapim1 $RELEASE ${arch}
      - ./extract-merge-upload.sh bananapim2 $RELEASE ${arch}
      - ./extract-merge-upload.sh bananapim3 $RELEASE ${arch}
      - ./extract-merge-upload.sh beagleboneblack $RELEASE ${arch}
      - ./extract-merge-upload.sh cubieboard $RELEASE ${arch}
      - ./extract-merge-upload.sh cubieboard2 $RELEASE ${arch}
      - ./extract-merge-upload.sh odroid-c2 $RELEASE ${arch}
      - ./extract-merge-upload.sh odroid-xu $RELEASE ${arch}
      - ./extract-merge-upload.sh raspberrypi2 $RELEASE ${arch}
      - ./extract-merge-upload.sh raspberrypi3 $RELEASE ${arch}
    privileged: true
    when:
      platform: linux/arm
      
     
matrix:
  include:
    - platform: linux/arm
      container: armv7/armhf-debian:8
      git: syncloud/armhf-drone-git
      arch: armhf
    - platform: linux/amd64
      container: debian:8
      git: plugins/git
      arch: amd64
