---
kind: pipeline
name: amd64-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-amd64
  commands:
  - ./tools/extract.sh amd64 amd64-base.img buster
  privileged: true

- name: boot
  image: syncloud/build-deps-amd64
  commands:
  - ./tools/boot.sh amd64 syncloud-amd64-20.06.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-amd64
  commands:
  - ./tools/rootfs.sh amd64 amd64 syncloud-amd64-20.06.img 20.06 buster
  privileged: true

- name: virtualbox prepare
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: virtualbox_host
    key:
      from_secret: virtualbox_key
    source:
    - syncloud-amd64-20.06.img
    - create_vbox_image.sh
    target: /data/drone-buster
    username: root

- name: virtualbox
  image: appleboy/drone-ssh
  settings:
    command_timeout: 20m
    host:
      from_secret: virtualbox_host
    key:
      from_secret: virtualbox_key
    port: 22
    script:
    - cd /data/drone-buster
    - ./create_vbox_image.sh syncloud-amd64-20.06.img
    script_stop: true
    username: root
  privileged: true

- name: zip
  image: syncloud/build-deps-amd64
  commands:
  - ./tools/zip.sh syncloud-amd64-20.06.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-amd64-20.06.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

...
