---
kind: pipeline
name: bananapim3-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh bananapim3 bananapim3-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh bananapim3 syncloud-bananapim3-21.01.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/rootfs.sh bananapim3 arm syncloud-bananapim3-21.01.img 21.01 buster
  privileged: true


- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-bananapim3-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-bananapim3-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: rock64-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh rock64 rock64-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh rock64 syncloud-rock64-21.01.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/rootfs.sh rock64 arm syncloud-rock64-21.01.img 21.01 buster
  privileged: true


- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-rock64-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-rock64-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: helios4-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh helios4 helios4-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh helios4 syncloud-helios4-21.01.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/rootfs.sh helios4 arm syncloud-helios4-21.01.img 21.01 buster
  privileged: true


- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-helios4-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-helios4-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: helios64-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh helios64 helios64-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh helios64 syncloud-helios64-21.01.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/rootfs.sh helios64 arm syncloud-helios64-21.01.img 21.01 buster
  privileged: true


- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-helios64-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-helios64-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: raspberrypi-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh raspberrypi raspberrypi-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh raspberrypi syncloud-raspberrypi-21.01.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/rootfs.sh raspberrypi arm syncloud-raspberrypi-21.01.img 21.01 buster
  privileged: true


- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-raspberrypi-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-raspberrypi-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: raspberrypi2-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh raspberrypi2 raspberrypi2-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh raspberrypi2 syncloud-raspberrypi2-21.01.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/rootfs.sh raspberrypi2 arm syncloud-raspberrypi2-21.01.img 21.01 buster
  privileged: true


- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-raspberrypi2-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-raspberrypi2-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: odroid-xu3and4-all-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh odroid-xu3and4 odroid-xu3and4-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh odroid-xu3and4 syncloud-odroid-xu3and4-21.01.img 3G
  privileged: true

- name: rootfs
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/rootfs.sh odroid-xu3and4 arm syncloud-odroid-xu3and4-21.01.img 21.01 buster
  privileged: true


- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-odroid-xu3and4-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-odroid-xu3and4-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

---
kind: pipeline
name: odroid-xu3and4-sd-buster

platform:
  os: linux
  arch: amd64

steps:
- name: extract
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/extract.sh odroid-xu3and4 odroid-xu3and4-base.img
  privileged: true

- name: boot
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/boot.sh odroid-xu3and4 syncloud-odroid-xu3and4-sd-21.01.img 10M
  privileged: true



- name: zip
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./tools/zip.sh syncloud-odroid-xu3and4-sd-21.01.img
  privileged: true

- name: artifact
  image: appleboy/drone-scp
  settings:
    command_timeout: 2m
    host:
      from_secret: artifact_host
    key:
      from_secret: artifact_key
    source: syncloud-odroid-xu3and4-sd-21.01.img*.xz
    target: /home/artifact/repo/image
    username: artifact

- name: cleanup
  image: syncloud/build-deps-buster-amd64
  commands:
  - ./cleanup.sh
  privileged: true
  when:
    status:
    - failure
    - success

...
