language: c
before_script:
- echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
script:
- sudo ./syncloud.sh
- sudo pip install -r dev_requirements.txt
- sudo py.test syncloud-verify.py --email=build@syncloud.it --password=travispassword123
